# Generated by Django 4.2.6 on 2023-10-05 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ATTN_Number', models.IntegerField()),
                ('Movie_Name', models.CharField(max_length=255)),
                ('Seat_Number', models.CharField(max_length=255)),
                ('Show_Time', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=4)),
                ('genre', models.CharField(max_length=255)),
            ],
        ),
    ]
